import { MaterializeModule, ModuleBuilder, moduleImport,  TestClass, TestClassUsing } from "../module/ModuleBuilder";
import { value } from "../resolvers/ValueResolver";
import { singleton } from "../resolvers/ClassSingletonResolver";

const m = ModuleBuilder.empty('')

const m222 = m
  .define('a', value(1))
  .define('a1', value('string'))
  .define('ab1', value('string'))
  .define('abc1', value('string'))
  .define('abcd1', value('string'))
  .define('abcde1', value('string'))
  .define('abcdef1', value('string'))
  .define('abcdefg1', value('string'))
  .define('abcdefgh1', value('string'))
  .define('a2', value('string'))
  .define('ab2', value('string'))
  .define('abc2', value('string'))
  .define('abcd2', value('string'))
  .define('abcde2', value('string'))
  .define('abcdef2', value('string'))
  .define('abcdefg2', value('string'))
  .define('abcdefgh2', value('string'))
  .define('a3', value('string'))
  .define('ab3', value('string'))
  .define('abc3', value('string'))
  .define('abcd3', value('string'))
  .define('abcde3', value('string'))
  .define('abcdef3', value('string'))
  .define('abcdefg3', value('string'))
  .define('abcdefgh3', value('string'))
  .define('a4', value('string'))
  .define('ab4', value('string'))
  .define('abc4', value('string'))
  .define('abcd4', value('string'))
  .define('abcde4', value('string'))
  .define('abcdef4', value('string'))
  .define('abcdefg4', value('string'))
  .define('abcdefgh4', value('string'))
  .define('a5', value('string'))
  .define('ab5', value('string'))
  .define('abc5', value('string'))
  .define('abcd5', value('string'))
  .define('abcde5', value('string'))
  .define('abcdef5', value('string'))
  .define('abcdefg5', value('string'))
  .define('abcdefgh5', value('string'))
  .define('a6', value('string'))
  .define('ab6', value('string'))
  .define('abc6', value('string'))
  .define('abcd6', value('string'))
  .define('abcde6', value('string'))
  .define('abcdef6', value('string'))
  .define('abcdefg6', value('string'))
  .define('abcdefgh6', value('string'))
  .define('a7', value('string'))
  .define('ab7', value('string'))
  .define('abc7', value('string'))
  .define('abcd7', value('string'))
  .define('abcde7', value('string'))
  .define('abcdef7', value('string'))
  .define('abcdefg7', value('string'))
  .define('abcdefgh7', value('string'))
  .define('a8', value('string'))
  .define('ab8', value('string'))
  .define('abc8', value('string'))
  .define('abcd8', value('string'))
  .define('abcde8', value('string'))
  .define('abcdef8', value('string'))
  .define('abcdefg8', value('string'))
  .define('abcdefgh8', value('string'))
  .define('a9', value('string'))
  .define('ab9', value('string'))
  .define('abc9', value('string'))
  .define('abcd9', value('string'))
  .define('abcde9', value('string'))
  .define('abcdef9', value('string'))
  .define('abcdefg9', value('string'))
  .define('abcdefgh9', value('string'))
  .define('num', value(123));

const mmm = m
  .define('imported', moduleImport(m222))
  .define('b', value('string'))
  .define('sdf', singleton(TestClass), ['imported.num', 'b'])
  .define('sdf2', singleton(TestClassUsing), ['sdf']);
type Mat = MaterializeModule<typeof mmm>;
