name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 15.x ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: yarn build
      - run: yarn test --coverage

      - name: Copy core documentation
        run: cp ./README.md ./packages/core/README.md

      - uses: codecov/codecov-action@v1
        with:
          files: ./coverage/clover.xml
          fail_ci_if_error: true
          verbose: true

      - name: Publish core
        uses: JS-DevTools/npm-publish@v1
        if: github.ref == 'refs/heads/master'
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/core/package.json
