name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x, 17.x, 18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install
      - run: yarn build
      - run: yarn test:coverage

      - uses: codecov/codecov-action@v1
        with:
          files: ./coverage/clover.xml
          fail_ci_if_error: true
          verbose: true

  publish:
    runs-on: ubuntu-latest

    needs:
      - build

    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: yarn install
      - run: yarn build

      - name: Copy core documentation
        run: cp ./README.md ./packages/core/README.md

      - name: Publish core
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/core/package.json

      - name: Publish react integration
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/react/package.json
