name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 23.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install --ignore-scripts
      - run: yarn build
      - run: yarn test:coverage

      - uses: codecov/codecov-action@v4
        with:
          files: ./coverage/clover.xml
          fail_ci_if_error: true
          verbose: true
          token: ${{ secrets.CODECOV_TOKEN }} # required

  publish:
    runs-on: ubuntu-latest

    needs:
      - build

    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - run: yarn install
      - run: yarn build

      - name: Copy core documentation
        run: cp ./README.md ./packages/core/README.md

      - name: Publish core
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/core/package.json

      - name: Publish react integration
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: packages/react/package.json
